api_login_check:
  path: /api/login_check

get_client_by_nic:
  path: /api/user/client/nci/{nic}
  methods: [GET]
  defaults:
    _controller: App\Controller\ClientController::getClientByNic
get_client_by_phone_number:
  path: /api/user/client/phone-number/{phoneNumber}
  methods: [GET]
  defaults:
    _controller: App\Controller\ClientController::getClientByPhoneNumber

#make_deposit:
#  path: /api/user/transactions
#  methods: [POST]
#  defaults:
#    _controller: App\Controller\ClientController::makeDeposit