# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
    acme_api.event.jwt_created_listener:
        class: App\Token\JWTUpdateListener
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTUpdate }
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    get_transaction_by_code:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { 'transfertCode': 'exact' } ]
        tags: [ { name: 'api_platform.filter',id: 'get_transaction_by_code' } ]
    get_client_by_nci:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { 'nicNumber': 'exact' } ]
        tags: [ { name: 'api_platform.filter',id: 'get_client_by_nci' } ]
    get_by_id:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { 'id': 'exact' } ]
        tags: [ { name: 'api_platform.filter',id: 'get_by_id' } ]
    get_transaction_by_date:
        parent: 'api_platform.doctrine.orm.date_filter'
        arguments: [ { 'depositAt': 'exact' , 'withdrewAt': ~} ]
        tags: [ 'api_platform.filter' ]
