App\Entity\Transaction:
  properties:
    amount:
      - NotNull:
          message: 'Ce champ est obligatore'
          groups: ['make_withdrawal', 'make_a_deposit']
      - Regex:
          pattern: '/\d/'
          match: true
          message: 'Le montant de la transaction ne doit pas contenir de lettre.'
          groups: ['make_withdrawal', 'make_a_deposit']
      - GreaterThanOrEqual:
          value: 1
          message: '{{ value }} le montant minimal de transfert est de 1.'
          groups: ['make_withdrawal']
    depositClient:
      - Valid:
          groups: ['make_a_deposit']
    withdrawalClient:
      - Valid:
          groups: ['make_a_deposit']
